[{
    "company_name":"hcl",
    "date":ISODate("2020-10-15"),
    "students_appeared":"Dines,Saipriya,Diviyash,Keerthinaidu,Mani"
},
{
    "company_name":"cts",
    "date":ISODate("2020-10-18"),
    "students_appeared":"Hari,Ashwin,Kamesh,Venkatesh,Bharath"
},
{
    "company_name":"tcs",
    "date":ISODate("2020-10-17"),
    "students_appeared":"Vamsi,Deepak,Levin,Gokul,sangeeth"
},
{
    "company_name":"zoho",
    "date":ISODate("2020-10-25"),
    "students_appeared":"Sivaranjani,Prem,Siva,Anu,Asma"
},
{
    "company_name":"guvi",
    "date":ISODate("2020-10-29"),
    "students_appeared":"Jenny,Mike,Sindhu,Preetha,Meghena"
}]